# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# EXAMPLES:
# https://github.com/filipesilva/angular-cli/blob/c6bf54ea97f8e8086cc4d7fd062e706323899226/docs/documentation/stories/continuous-integration.md
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.3-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "install-npm"
          # This will install all core dependencies as well as landing page dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
